# -*- coding: utf-8 -*-
"""flair-LER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ixk1uU8kK2dW1Z-2oPWrJxpuo8PeH6KY

#Flair
"""

!pip install flair

from flair.data import Corpus
from flair.datasets import ColumnCorpus

# define columns
columns = {0: 'text', 1: 'ner'}

# this is the folder in which train, test and dev files reside
data_folder = '/content/drive/My Drive/Projects/Legal.AI/Dataset/hk45anno'

# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='train.txt',
                              test_file='test.txt',
                              dev_file='dev.txt')

print(corpus.train[0].to_tagged_string('ner'))

len(corpus.train)

from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings, FlairEmbeddings

# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
print(tag_dictionary)

# 4. initialize embeddings
embedding_types = [

    WordEmbeddings('glove'),

    # comment in this line to use character embeddings
    # CharacterEmbeddings(),

    # comment in these lines to use flair embeddings
    FlairEmbeddings('news-forward'),
    FlairEmbeddings('news-backward'),
]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

# 5. initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)

# 6. initialize trainer
from flair.trainers import ModelTrainer

trainer: ModelTrainer = ModelTrainer(tagger, corpus)

# 7. start training
trainer.train('resources/taggers/example-ner',
              learning_rate=0.1,
              mini_batch_size=8,
              max_epochs=5000,
              embeddings_storage_mode='gpu')

# load the model you trained
model = SequenceTagger.load('/content/resources/taggers/example-ner/final-model.pt')

from flair.data import Sentence

# create example sentence
sentence = Sentence("""the term of this agreement shall commence on january 15 , 1998 (" commencement date ") and terminate on december 31. 2000 (" termination date ") .
dated effective january 15 , 1998 .
this mutual confidentiality agreement (“ agreement ”) , effective as of the 22 day of february , 2001 ( the “ effective date ”) is by and between gupta pvt . ltd (“ xxx ”) , a corporation with an address at sector 37 faridabad , and university hospitals of cleveland (“ uhc ”) , with an address at 11100 euclid avenue , cleveland , ohio 44106 .
this management services agreement (“ agreement ” or “ management agreement ”) is dated as of , 2011 by and between the hospital authority of floyd county , a hospital authority organized and existing pursuant to o.c.g.a . §§ 31-7-70 et seq . (“ authority ”) and polk medical center , inc. , a georgia nonprofit corporation (“ manager ”) .
1.1 term . unless earlier terminated , this agreement shall be effective from the commencement date of the hospital lease (“ effective date ”) until the termination date , defined in section 7.03 , unless terminated earlier by the parties ( the “ operating period ”) .
this lease and operating agreement ( the " lease ") , is made and entered into as of the 19th day of march , 2008 , by and among the county of bladen , a north carolina political subdivision , doing business as bladen county hospital ( the “ county ” or the “ landlord ”) and cumberland county hospital system , inc. , a north carolina nonprofit corporation , doing business as cape fear valley health care system (“ cape fear valley ” or the " tenant ") .
the initial term ( the “ initial term ”) of this lease is five ( 5 ) years , commencing on 19 march 2008 ( the " commencement date ") , and ending on 20 april 2013 ( the " termination date ") .
this exclusive business cooperation agreement ( this " agreement ") is made and entered into by and between the following parties on april 29 , 2004 in beijing . party a : beijing raisechina biotech , inc . address : suite 704 , 26 information road , haidian district , beijing 100083 , p.r.china and party b : beijing dongjun hospitals investment and management co. , ltd . address : 2501 , china world tower 1 , no . 1 jianguomenwai avenue , beijing 100004 , p. r. china
by and among test systems strategies , inc . ( a delaware corporation ) , credence systems corporation , summit design , inc. and test systems strategies , inc . ( an oregon corporation ) dated as of may 19 , 1997
this contract is for a term of five ( 5 ) years , beginning on the 12th day of december , 2018 and ending the 30th day of november , 2023 .
""")

# predict tags and print
model.predict(sentence)

print(sentence.to_tagged_string())

# iterate over entities and print
for entity in sentence.get_spans('ner'):
    print(entity)



"""#Scapy"""

import pandas as pd

df = pd.read_json('/content/hk_45-final_annotated_contracts.json1', lines=True)

del df['id']

del df['meta']
del df['annotation_approver']

df

TRAIN_DATA = []
for i in range(len(df)):
  t = (df['text'][i], {'entities': [tuple(ent) for ent in df['labels'][i]]})
  TRAIN_DATA.append(t)

TRAIN_DATA

!pip install spacy
!python -m spacy download en_core_web_sm

# Import and load the spacy model
import spacy
nlp=spacy.load("en_core_web_sm") 

# Getting the ner component
ner=nlp.get_pipe('ner')

# Adding labels to the `ner`

for _, annotations in TRAIN_DATA:
  for ent in annotations.get("entities"):
    ner.add_label(ent[2])

# Resume training
optimizer = nlp.resume_training()
move_names = list(ner.move_names)

# List of pipes you want to train
pipe_exceptions = ["ner", "trf_wordpiecer", "trf_tok2vec"]

# List of pipes which should remain unaffected in training
other_pipes = [pipe for pipe in nlp.pipe_names if pipe not in pipe_exceptions]

# Importing requirements
from spacy.util import minibatch, compounding
import random

# Begin training by disabling other pipeline components
with nlp.disable_pipes(*other_pipes) :

  sizes = compounding(1.0, 4.0, 1.001)
  # Training for 30 iterations     
  for itn in range(30):
    # shuffle examples before training
    random.shuffle(TRAIN_DATA)
    # batch up the examples using spaCy's minibatch
    batches = minibatch(TRAIN_DATA, size=sizes)
    # ictionary to store losses
    losses = {}
    for batch in batches:
      texts, annotations = zip(*batch)
      # Calling update() over the iteration
      nlp.update(texts, annotations, sgd=optimizer, drop=0.35, losses=losses)
      print("Losses", losses)

test_text = """Amazon-Customer Agreement
Welcome to Amazon.in. Amazon Seller Services Private Limited and its affiliates provide access to the Amazon.in website (the "website") to you subject to the conditions set out on this page.
Please read these conditions carefully before using the Amazon.in website. By using the Amazon.in website, you signify your agreement to be bound by these conditions.
In addition, when you use any current or future Amazon.in service (eg. Wish List or Marketplace) ("Amazon Service"), you will also be subject to the terms, guidelines and conditions applicable to that Amazon Service. ("Terms"). If these Conditions of Use are inconsistent with such Terms, the Terms will control.
These "Conditions of Use" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.
•	Conditions Relating to Your Use of Amazon.in
•	Notice and Procedure for Making Claims of Infringement
•	Notice and Procedure for Notifying Amazon.in of Objectionable Content
Conditions Relating to Your Use of Amazon.in
1. Your Account
If you use the website, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer to prevent unauthorised access to your account. You agree to accept responsibility for all activities that occur under your account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorised manner. Please ensure that the details you provide us with are correct and complete and inform us immediately of any changes to the information that you provided when registering. You can access and update much of the information you provided us with in the Your Account area of the website. You agree and acknowledge that you will use your account on the website to purchase products only for your personal use and not for business purposes. Should you wish to order products for business purposes, please create a business account on Amazon.in/business. Amazon.in reserves the right to refuse access to the website, terminate accounts, remove or edit content at any time without notice to you.
2. Privacy
Please review our Privacy Notice, which also governs your visit to Amazon.in, to understand our practices. The personal information / data provided to us by you during the course of usage of Amazon.in will be treated as strictly confidential and in accordance with the Privacy Notice and applicable laws and regulations. If you object to your information being transferred or used, please do not use the website.
3. E-Platform for Communication
You agree, understand and acknowledge that the website is an online platform that enables you to purchase products listed on the website at the price indicated therein at any time from any location. You further agree and acknowledge that Amazon is only a facilitator and is not and cannot be a party to or control in any manner any transactions on the website. Accordingly, the contract of sale of products on the website shall be a strictly bipartite contract between you and the sellers on Amazon.in.
4. Access to Amazon.in
We will do our utmost to ensure that availability of the website will be uninterrupted and that transmissions will be error-free. However, due to the nature of the Internet, this cannot be guaranteed. Also, your access to the website may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or services at any time without prior notice. We will attempt to limit the frequency and duration of any such suspension or restriction.
5. Licence for website access
Subject to your compliance with these Conditions of Use and payment of applicable fees, if any, Amazon Seller Services Private Limited grants you a limited licence to access and make personal use of this website, but not to download (other than page caching) or modify it, or any portion of it, except with express written consent of Amazon Seller Services Private Limited and / or its affiliates, as may be applicable. This licence does not include any resale or commercial use of this website or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this website or its contents; any downloading or copying of account information for the benefit of another seller; or any use of data mining, robots, or similar data gathering and extraction tools.
This website or any portion of this website (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without express written consent of Amazon Seller Services Private Limited and / or its affiliates, as may be applicable.
You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of Amazon.in and its affiliates without express written consent. You may not use any meta tags or any other "hidden text" utilising Amazon Seller Services Private Limited's or its affiliates' names or trademarks without the express written consent of Amazon Seller Services Private Limited and / or its affiliates, as applicable. Any unauthorised use terminates the permission or license granted by Amazon Seller Services Private Limited and / or its affiliates, as applicable.
You are granted a limited, revocable, and non-exclusive right to create a hyperlink to the Welcome page of Amazon.in as long as the link does not portray Amazon Seller Services Private Limited, Amazon.in, their affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any Amazon.in logo or other proprietary graphic or trademark as part of the link without express written consent of Amazon Seller Services Private Limited and / or its affiliates, as may be applicable.
6. Your Conduct
You must not use the website in any way that causes, or is likely to cause, the website or access to it to be interrupted, damaged or impaired in any way You understand that you, and not Amazon.in, are responsible for all electronic communications and content sent from your computer to us and you must use the website for lawful purposes only. You must not use the website for any of the following:
•	for fraudulent purposes, or in connection with a criminal offense or other unlawful activity
•	to send, use or reuse any material that does not belong to you; or is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libelous, obscene, pornographic, pedophilic or menacing; ethnically objectionable, disparaging or in breach of copyright, trademark, confidentiality, privacy or any other proprietary information or right; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any "spam
•	to cause annoyance, inconvenience or needless anxiety

7. Reviews, comments, communications and other content
Users of this website may post reviews, comments and other content; send communications; and submit suggestions, ideas, comments, questions, or other information, as long as the content is not illegal, obscene, abusive, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties, or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." In the event a user uses a false e-mail address, impersonates any person or entity, or otherwise misleads as to the origin of any content. Amazon.in reserves the right (but not the obligation) to remove, refuse, delete or edit any content that in the sole judgement of Amazon.in violates these Conditions of use and, or terminate your permission to access or use this website.
If you do post content or submit material, and unless we indicate otherwise, you


1.	(a) grant Amazon Seller Services Private Limited and its affiliates a non-exclusive, royalty-free, irrevocable, perpetual and fully sublicensable rights to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media; and
2.	(b) Amazon Seller Services Private Limited and its affiliates and sublicensees the right to use the name that you submit in connection with such content, if they choose.
You agree that the rights you grant above are irrevocable during the entire period of protection of your intellectual property rights associated with such content and material. You agree to waive your right to be identified as the author of such content and your right to object to derogatory treatment of such content. You agree to perform all further acts necessary to perfect any of the above rights granted by you to Amazon Seller Services Private Limited, including the execution of deeds and documents, at its request.
You represent and warrant that you own or otherwise control all of the rights to the content that you post or that you otherwise provide on or through the website; that, as at the date that the content or material is submitted to Amazon.in: (i) the content and material is accurate; (ii) use of the content and material you supply does not breach any applicable Amazon.in policies or guidelines and will not cause injury to any person or entity (including that the content or material is not defamatory); (iii) the content is lawful. You agree to indemnify Amazon Seller Services Private Limited and its affiliates for all claims brought by a third party against it or its affiliates arising out of or in connection with a breach of any of these warranties.
8. Claims against Objectionable Content
Because Amazon.in lists millions of products for sale offered by sellers on the website and hosts many thousands of comments, it is not possible for us to be aware of the contents of each product listed for sale, or each comment or review that is displayed. Accordingly, Amazon.in operates on a "notice and takedown" basis. If you believe that any content on the website is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libelous, obscene, pornographic, pedophilic or menacing; ethnically objectionable, disparaging; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, (" Objectionable Content "), please notify us immediately by following our Notice and Procedure for Making Claims of Right Infringements. Once this procedure has been followed, Amazon.in will make all reasonable endeavours to remove such Objectionable Content complained about within a reasonable time.
9. Copyright, authors' rights and database rights
All content included on the website, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of Amazon Seller Services Private Limited, its affiliates or its content suppliers and is protected by India and international copyright, authors' rights and database right laws. The compilation of all content on this website is the exclusive property of Amazon Seller Services Private Limited and its affiliates and is protected by laws of India and international copyright and database right laws. All software used on this website is the property of Amazon Seller Services Private Limited, its affiliates or its software suppliers and is protected by India and international copyright and author' rights laws.
You may not systematically extract/ or re-utilise parts of the contents of the website without Amazon Seller Services Private Limited and / or its affiliate's (as may be applicable) express written consent. In particular, you may not utilise any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilisation of any substantial parts of this website, without Amazon Seller Services Private Limited and / or its affiliate's (as may be applicable) express written consent. You may also not create and/ or publish your own database that features substantial (eg: prices and product listings) parts of this website without Amazon Seller Services Private Limited and / or its affiliate's (as may be applicable) express written consent.
10. Intellectual Property Claims
Amazon Seller Services Private Limited and its affiliates respect the intellectual property of others. If you believe that your intellectual property rights have been used in a way that gives rise to concerns of infringement, please follow our Notice and Procedure for Making Claims of Right Infringements.
11. Trademarks
AMAZON.IN, AMAZON, THE AMAZON LOGO, AND YOU'RE DONE, 1-CLICK, EARTH'S BIGGEST SELECTION, PURCHASE CIRCLES, LISTMANIA, NEW FOR YOU, AMAZON.COM, AMAZON.DE, AMAZON.FR, AMAZON.IT, AMAZON.CO.JP, AMAZON.CA, AMAZON HONOR SYSTEM, PAYPAGE and other marks indicated on our website are trademarks or registered trademarks of Amazon.com, Inc. or its subsidiaries (collectively "Amazon"), in the European Union and/or other jurisdictions. Amazon.in's graphics, logos, page headers, button icons, scripts and service names are the trademarks or trade dress of Amazon. Amazon's trademarks and trade dress may not be used in connection with any product or service that is not Amazon's, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Amazon. All other trademarks not owned by Amazon that appear on this website are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Amazon.
12. Patents
One or more patents apply to the website and to the features and services accessible via the website, including without limitation: US Patent Nos. 5,715,399; 5,960,411; 6,006,225; 6,029,141; 6,064,980; 6,144,958; 6,169,986; 6,185,558; 6,266,649; 6,317,722; 6,360,254; 6,366,910; 6,401,084 and all corresponding foreign counterparts.
13. Disclaimer
You acknowledge and undertake that you are accessing the services on the website and transacting at your own risk and are using your best and prudent judgment before entering into any transactions through the website. You further acknowledge and undertake that you will use the website to order products only for your personal use and not for business purposes. We shall neither be liable nor responsible for any actions or inactions of sellers nor any breach of conditions, representations or warranties by the sellers or manufacturers of the products and hereby expressly disclaim and any all responsibility and liability in that regard. We shall not mediate or resolve any dispute or disagreement between you and the sellers or manufacturers of the products.
We further expressly disclaim any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, merchantability, fitness for a particular purpose, or legality of the products listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website. While we have taken precautions to avoid inaccuracies in content, this website, all content, information (including the price of products), software, products, services and related graphics are provided as is, without warranty of any kind. We do not implicitly or explicitly support or endorse the sale or purchase of any products on the website. At no time shall any right, title or interest in the products sold through or displayed on the website vest with Amazon nor shall Amazon have any obligations or liabilities in respect of any transactions on the website.
14. Indemnity and Release
You shall indemnify and hold harmless Amazon Seller Services Private Limited, its subsidiaries, affiliates and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of your breach of these Conditions of Use or any document incorporated by reference, or your violation of any law, rules, regulations or the rights of a third party.
You hereby expressly release Amazon Seller Services Private Limited and/or its affiliates and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions/inactions of the vendors and specifically waiver any claims or demands that you may have in this behalf under any statute, contract or otherwise.
15. Children
Use of Amazon.in is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 years, you may use Amazon.in only with the involvement of a parent or guardian.
16. Other Businesses
Parties other than Amazon Seller Services Private Limited and its affiliates may operate stores, provide services, or sell product lines on Amazon.in. For example, businesses and individuals offer products via Marketplace. In addition, we provide links to the websites of affiliated companies and certain other businesses. We are not responsible for examining or evaluating, and we do not warrant or endorse the offerings of any of these businesses or individuals, or the content of their websites. Amazon Seller Services Private Limited does not assume any responsibility or liability for the actions, products, and content of any of these and any other third-parties. You can tell when a third-party is involved in your transactions, and we may share customer information related to those transactions with that third-party. You should carefully review their privacy statements and other conditions of use.
17. Communications
When you visit Amazon.in, you are communicating with us electronically. You will be required to provide a valid phone number while placing an order with us. We may communicate with you by e-mail, SMS, phone call or by posting notices on the website or by any other mode of communication. For contractual purposes, you consent to receive communications (including transactional, promotional and/or commercial messages), from us with respect to your use of the website and/or your order placed on the website.
18. Losses
We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when you commenced using the website.
19. Alteration of Service or Amendements to the Conditions
We reserve the right to make changes to our website, policies, and these Conditions of Use at any time. You will be subject to the policies and Conditions of Use in force at the time that you use the website or that you order goods from us, unless any change to those policies or these conditions is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.
20. Events beyond our reasonable control
We will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights.
21. Waiver
If you breach these conditions and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these conditions.
22. Governing law and Jurisdiction
These conditions are governed by and construed in accordance with the laws of India. You agree, as we do, to submit to the exclusive jurisdiction of the courts at Delhi.
23. Our Details
This website is operated by Amazon Seller Services Private Limited.
For the Amazon.in website, you could contact us by visiting: www.amazon.in/gp/help/contact-us
24. Amazon Software Terms
In addition to these Conditions of Use, the terms found here apply to any software (including any updates or upgrades to the software and any related documentation) that we make available to you from time to time for your use in connection with Amazon Services (the "Amazon Software").
25. Sanctions and Export Policy
You may not use any Amazon Service if you are the subject of U.S. sanctions or of sanctions consistent with U.S. law imposed by the governments of the country where you are using Amazon Services. You must comply with all U.S. or other export and re-export restrictions that may apply to goods, software (including Amazon Software), technology and services.
Notice and Procedure for Making Claims of Right Infringements
If you believe that your rights are being infringed, you may fill out and submit the Notice Form. We respond expeditiously to rights owners and their agents who complete and submit the Notice Form to communicate concerns about any alleged infringement.
Upon receipt of a Notice Form we may take certain actions, including removing information or an item, all of which are taken without any admission as to liability and without prejudice to any rights, remedies or defenses, all of which are expressly reserved. Furthermore, in submitting a Notice Form, you grant to Amazon the right to use, reproduce, modify, adapt, publish, translate, create derivative works from, and display its content throughout the world in any media. This includes forwarding the Notice Form to the parties involved in the provision of the allegedly infringing content. You agree to indemnify Amazon for all claims brought by a third party against Amazon arising out of or in connection with the submission of a Notice Form.
Note on Third Party Seller Listings: Please keep in mind that Third Party Seller listings are merely hosted on Amazon.in and are posted solely at the direction of Third Party Sellers who may be contacted via their "Seller Information" page, accessible from any of their listings.
ASIN and ISBN-10, Defined: "ASIN" stands for Amazon Standard Item (or Identification) Number and is a ten (10) character identifier. It can be found below any listing under "Product Details". "ISBN-10" stands for International Standard Book Number and is a ten (10) digit identifier that can be found on some book listings under "Product Details".
Important Warning: giving false, misleading or inaccurate information in the Notice Form to Amazon may result in civil and/or criminal liability. You should contact a legal advisor should you have any questions.
Notice Form:
If you believe that your rights are being violated by an item or information on the Amazon.in site, you may fill out and submit the Notice Form (below). This signed form can be sent via E-mail PDF or Fax to the Grievance Officer:
Name: Iniyan R
e-mail PDF: grievance-officer@amazon.in
Subject Line: Claim of Infringement or Fax: 040 – 39922887
or
Amazon Seller Services Pvt. Ltd.
Ground Floor
Eros Plaza, Eros Corporate Tower
Nehru Place
New Delhi 110019
(We will accept a signed PDF via e-mail with the subject line "Claim of Infringement" or Fax, unless by prior agreement we have agreed with you for an alternative receipt mechanism).
Please fill out the Notice form using the corresponding numbered paragraphs to frame your communication.
Notice Form
Re: www.Amazon.in
I, [INSERT FULL NAME AND TITLE ] of [COMPANY NAME, IF APPLICABLE] , state as follows:

1.	Contact information
:(a) Your and/ or your company's name, address, telephone number and contact email address; (b)The contact email address and/or name which we will provide to Third Party Sellers (if relevant) so they may contact you to resolve any issues regarding your notification to us. If you do not provide a separate contact email, you authorize us to use the contact information you provide in (1)(a).
2.	Listing's ASIN (or ISBN-13 if applicable) and Allegation of Infringed Right:
(a) The listing's ASIN/ISBN-13 number or detailed description of where the information that you claim is infringing your rights is located on the site; if regarding a Third Party Seller listing please also provide the name used to identify the Seller on the site (look for "dispatched and sold by _____" or "by ______" in the listing). (b) A description of your intellectual property right(s) that you claim has/have been infringed (e.g. copyright, trademark or patent) by the information of/for this ASIN/ISBN-13. [REPEAT (2)(a-b) as necessary for multiple items, see example Notice Form here.]
3.	Include the following statement: "I have a good faith belief that the portion of the listing(s) described above violate(s) the intellectual property rights owned by the intellectual property owner or its agent, nor is such use otherwise permissible under law."
4.	Include the following statement: "I represent that the information in this notification is true and correct and that I am the intellectual property owner or authorised to act on behalf of the intellectual property owner for the rights described above."
5.	Sign the Notice Form.
Notice and Procedure for Notifying Amazon.in of Objectionable Content
If you believe that any content on, or advertised for sale on, the website contains any Objectionable Content as defined under Section 8 above, please notify us immediately by copying the Notice to Amazon.in of Objectionable Content below into your word processor program, complete it in accordance with the instructions set out in the Notice and send a signed copy via E-mail PDF or Fax to the Grievance Officer:
Name: Iniyan R
e-mail PDF: grievance-officer@amazon.in
Subject Line: Claim of Objectionable Content
or
Fax: 040-39922887
or
Amazon Seller Services Private Limited
Ground Floor,
Eros Plaza, Eros Corporate Tower,
Nehru Place,
New Delhi 110019
Please note that this procedure is exclusively for notifying Amazon.in of Objectionable Content on or advertised for sale on the Amazon.in website. Please provide your address, telephone number, and e-mail address when sending the notice to us.
Important Warning: Giving false, misleading or inaccurate information in the Notice to Amazon.in may result in civil and/ or criminal liability.
Notice to Amazon.in of Objectionable Content
In the matter of Amazon.in
I, [Please set out your full name] of [please give your postal address], [please set your occupation] , says as follows:

1.	I refer to the website www.Amazon.in ("the website"). I make this statement in support of my giving Amazon.in notice that, via the website, it is causing or contributing to the publication of Objectionable Content.
2.	The Objectionable Content (delete whichever paragraph is not applicable): (a) appear in a book being sold by Amazon.in via the website entitled [please state the book name and its author]. The Objectionable Content appear on page [please state the page number(s) where you consider the words constitute Objectionable Content]. OR (b) appear on the website at [please cut and paste the address of the relevant Web page from the website where the Objectionable Content appears].
3.	The words/ content that I consider to be Objectionable Content are [please repeat the exact words you are complaining about].
4.	This content is Objectionable Content because [please state why you consider the content is Objectionable Content].
5.	I understand that this statement may be used in any court proceedings that may arise out of or relating to the Objectionable Content which I have complained about.
Statement of Truth
I declare the facts stated above to be true.
Signed:
Dated:
Please read the conditions of use carefully before using the Amazon.in website. By using the Amazon.in website, you signify your agreement to be bound by these conditions.
Amazon Software Terms
1. Use of the Amazon Software
You may use Amazon Software solely for purposes of enabling you to use and enjoy the Amazon Services as provided by Amazon, and as permitted by the Conditions of Use, these Amazon Software Terms and any Terms. You may not incorporate any portion of the Amazon Software into your own programs or compile any portion of it in combination with your own programs, transfer it for use with another service, or sell, rent, lease, lend, loan, distribute or sub-license the Amazon Software or otherwise assign any rights to the Amazon Software in whole or in part. You may not use the Amazon Software for any illegal purpose. We may cease providing any Amazon Software and we may terminate your right to use any Amazon Software at any time. Your rights to use the Amazon Software will automatically terminate without notice from us if you fail to comply with any of these Amazon Software Terms, the Conditions of Use or any other Terms. Additional third party terms contained within or distributed with certain Amazon Software that are specifically identified in related documentation may apply to that Amazon Software (or software incorporated with the Amazon Software) and will govern the use of such software in the event of a conflict with these Conditions of Use. All software used in any Amazon Service is the property of Amazon and/or its affiliates or its software suppliers and protected by laws of India including but not limited to any other applicable copyright laws.
2. Use of Third Party Services
When you use the Amazon Software, you may also be using the services of one or more third parties, such as a wireless carrier or a mobile platform provider. Your use of these third party services may be subject to the separate policies, terms of use, and fees of these third parties.
3. No Reverse Engineering
You may not, and you will not encourage, assist or authorize any other person to copy, modify, reverse engineer, decompile or disassemble, or otherwise tamper with, the Amazon Software, whether in whole or in part, or create any derivative works from or of the Amazon Software.
Updates
In order to keep the Amazon Software up-to-date, we may offer automatic or manual updates at any time and without notice to you.
Conditions of Sale (between Sellers and the Customer)
Please read these conditions carefully before placing an order for any products with the Sellers ("We" or "Our" or "Us", wherever applicable) on the Amazon.in (the website). These conditions signify your agreement to be bound by these conditions.
In addition, when you use any current or future Amazon.in service (eg: Wishlist or Marketplace or Amazon MP3 Service), you will also be subject to the terms, guidelines and conditions applicable to that service ("Terms"). If these Conditions of Sale are inconsistent with such Terms, the Terms will control.
1. Conditions Relating to the Sale of Products to You
This section deals with conditions relating to the sale of products on the website by us to you.
2. Our Contract
Your order is an offer to us to buy the product(s) in your order. When you place an order to purchase a product from us, you will receive an e-mail confirming receipt of your order and containing the details of your order (the "Order Confirmation E-mail"). The Order Confirmation E-mail is acknowledgement that we have received your order, and does not confirm acceptance of your offer to buy the product(s) ordered. We only accept your offer, and conclude the contract of sale for a product ordered by you, when the product is dispatched to you and an e-mail confirmation is sent to you that the product has been dispatched to you (the "Dispatch Confirmation E-mail"). If your order is dispatched in more than one package, you may receive a separate Dispatch Confirmation E-mail for each package, and each Dispatch Confirmation E-mail and corresponding dispatch will conclude a separate contract of sale between you and us for the product(s) specified in that Dispatch Confirmation E-mail.
Your contract is with us (the Sellers) and you confirm that the product(s) ordered by you are purchased for your internal / personal purpose and not for re-sale or business purpose. You authorize us to declare and provide declaration to any governmental authority on your behalf stating the aforesaid purpose of the products ordered by you on the website.
You can cancel your order for a product at no cost any time before we send the Dispatch Confirmation E-mail relating to that product.
Please note that we sell products only in quantities which correspond to the typical needs of an average household. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity typical for a normal household.
3. Returns
Please review our Returns Policy, which applies to products sold by us.
4. Pricing and availability
We list availability information for products sold by us on the website, including on each product information page. Beyond what we say on that page or otherwise on the website, we cannot be more specific about availability. Please note that dispatch estimates are just that. They are not guaranteed dispatch times and should not be relied upon as such. As we process your order, you will be informed by e-mail if any products you order turn out to be unavailable.
For more details, please review our Pricing policy and our Availability Guide, both of which apply to products ordered from us.
All prices are inclusive of VAT/CST, service tax, Goods and Services Tax ("GST"), duties and cesses as applicable - unless stated otherwise.
5. Taxes
You shall be responsible for payment of all fees/costs/charges associated with the purchase of products from us and you agree to bear any and all applicable taxes including but not limited to VAT/CST, service tax, GST, duties and cesses etc.
6. Health & Safety
By purchasing any product from our Home & Kitchen shop, you acknowledge that you have read and understood our Health & Safety Guidelines.
7. Children
Use of Amazon.in is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 years, you may purchase only with the involvement of a parent or guardian.
8. Communications
When you visit Amazon.in, you are communicating with us electronically. You will be required to provide a valid phone number while placing an order with us. We may communicate with you by e-mail, SMS, phone call or by posting notices on the website or by any other mode of communication. For contractual purposes, you consent to receive communications including SMS, e-mails or phone calls from us with respect to your order.
9. Losses
We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when a contract for the sale of goods by us to you was formed.
10. Alteration or Amendments to the Conditions
We reserve the right to make changes to our policies, and these Conditions of Sale at any time. You will be subject to the policies and Conditions of Sale in force at the time you order goods from us, unless any change to those policies or these conditions is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.
11. Events beyond our reasonable control
We will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights.
12. Waiver
If you breach these conditions and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these conditions.
13. Governing Law and Jurisdiction
These conditions are governed by and construed in accordance with the laws of India, and the application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. You agree, as we do, to submit to the exclusive jurisdiction of the courts at Delhi.
201909000
"""

# Testing the NER

test_text = """this contract shall be governed by the laws of the state of arizona . venue for any actions or lawsuits involving this contract will be in maricopa county superior court , phoenix , arizona .
"""
doc = nlp(test_text)
print("Entities", [(ent.text, ent.label_) for ent in doc.ents])
# print("Entities in '%s'" % test_text)
# for ent in doc.ents:
#   print(ent)

#display entities visually
import spacy
from spacy import displacy

#displacy.serve(doc, style="ent")
displacy.render(doc, style='ent', jupyter=True, options={'distance': 90})

# Output directory
from pathlib import Path
output_dir=Path('/content/')

# Saving the model to the output directory
if not output_dir.exists():
  output_dir.mkdir()
nlp.meta['name'] = 'ler'  # rename model
nlp.to_disk(output_dir)
print("Saved model to", output_dir)

# Loading the model from the directory
print("Loading from", output_dir)
nlp2 = spacy.load(output_dir)
assert nlp2.get_pipe("ner").move_names == move_names
doc2 = nlp2(' Dosa is an extremely famous south Indian dish')
for ent in doc2.ents:
  print(ent.label_, ent.text)